function sourceLabel(film){if(film.source==='wikipedia')return'WIKIPEDIA MATCH';return film.poster||film.backdrop?'CUSTOM ART':'NO ARTWORK'}
function googleImagesUrl(film,type='poster'){const suffix=type==='banner'?'movie banner backdrop landscape':'movie poster dvd cover';return`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(`${film.title}${film.year?` ${film.year}`:''} ${suffix}`)}`}
function renderLibrary(){
  $('filmCountPill').textContent=`${films.length} FILM${films.length===1?'':'S'}`;$('libraryEmpty').hidden=films.length>0;
  library.innerHTML=films.map((film,index)=>`<article class="film-row" data-id="${escapeHtml(film.id)}">
    <div class="library-poster-frame">${film.poster?`<img src="${escapeHtml(film.poster)}" alt=""/>`:`<div class="art-placeholder">POSTER<br>MISSING</div>`}</div>
    <div class="library-banner-frame">${film.backdrop?`<img src="${escapeHtml(film.backdrop)}" alt=""/>`:`<div class="art-placeholder">BANNER<br>MISSING</div>`}</div>
    <div><h3>${escapeHtml(film.title)}</h3><div class="row-meta">${escapeHtml(film.year||'Year unknown')} · ${sourceLabel(film)}${film.wikipediaTitle?`<br>Version: ${escapeHtml(film.wikipediaTitle)}`:''}<br>${escapeHtml((film.categories||[]).join(' · '))}</div><div class="art-status"><span class="art-chip ${film.poster?'ok':''}">POSTER ${film.poster?'✓':'—'}</span><span class="art-chip ${film.backdrop?'ok':''}">BANNER ${film.backdrop?'✓':'—'}</span></div></div>
    <div class="row-actions"><button data-action="versions">VERSIONS</button><button data-action="refind">REFIND ART</button><button data-action="google-poster">GOOGLE POSTER</button><button data-action="google-banner">GOOGLE BANNER</button><button data-action="edit">EDIT</button><button data-action="up" ${index===0?'disabled':''}>↑</button><button data-action="down" ${index===films.length-1?'disabled':''}>↓</button><button data-action="remove">×</button></div>
  </article>`).join('');
}
function openManualDialog(film=null){editingId=film?.id||null;$('manualDialogTitle').textContent=film?'Edit film':'Add film manually';$('manualSave').textContent=film?'Save changes':'Add film';$('manualTitle').value=film?.title||'';$('manualYear').value=film?.year||'';$('manualCategories').value=(film?.categories||[]).join(', ');$('manualPoster').value=film?.poster||'';$('manualBackdrop').value=film?.backdrop||'';$('manualOverview').value=film?.overview||'';manualDialog.showModal()}
function showScreen(asPreview){previewMode=!!asPreview;save();setupView.hidden=true;screenView.hidden=false;$('cameraControls').classList.toggle('production-hidden',!previewMode);$('screenEmpty').hidden=films.length>0;if(!films.length)return;filmIndex=clampIndex(filmIndex);virtualIndex=MIDDLE_REPEAT*films.length+filmIndex;buildCarousel();renderCategoryRows();updateTrack(0);updateFilmDetails();preloadArtwork();carousel.focus({preventScroll:true});location.hash=previewMode?'preview':'screen';if(!previewMode&&!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{})}
function showSetup(){spinning=false;locked=false;$('lockBadge').hidden=true;$('lockButton').textContent='LOCK';screenView.hidden=true;setupView.hidden=false;closePlaySequence();if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});location.hash='setup';renderLibrary()}
function buildCarousel(){if(!films.length){track.innerHTML='';return}const cards=[];for(let repeat=0;repeat<REPEATS;repeat++)films.forEach((film,index)=>{const v=repeat*films.length+index;cards.push(`<div class="poster-card" data-film-id="${escapeHtml(film.id)}" data-film-index="${index}" data-virtual-index="${v}">${film.poster?`<img src="${escapeHtml(film.poster)}" draggable="false" alt="${escapeHtml(film.title)} poster"/>`:`<div class="poster-placeholder">${escapeHtml(film.title)}</div>`}</div>`)});track.innerHTML=cards.join('')}
function preloadArtwork(){films.forEach(f=>[f.poster,f.backdrop].filter(Boolean).forEach(src=>{const i=new Image();i.src=src}))}
function cardMetrics(){const card=track.querySelector('.poster-card');if(!card)return{width:170,gap:18};const style=getComputedStyle(track);return{width:card.offsetWidth,gap:parseFloat(style.columnGap||style.gap)||18}}
function updateTrack(duration=0){if(!films.length)return;const{width,gap}=cardMetrics();track.style.transition=duration>0?`transform ${duration}ms cubic-bezier(.2,.8,.2,1)`:'none';track.style.transform=`translate3d(${-(virtualIndex*(width+gap)+width/2)}px,-50%,0)`;track.querySelectorAll('.poster-card.is-selected').forEach(el=>el.classList.remove('is-selected'));track.querySelector(`.poster-card[data-virtual-index="${virtualIndex}"]`)?.classList.add('is-selected')}
function mod(v,l){return((v%l)+l)%l}
function updateFilmDetails(){if(!films.length)return;const film=films[filmIndex];$('heroTitle').textContent=film.title;$('heroYear').textContent=film.year||'';$('heroCategories').textContent=(film.categories||[]).join(' · ');$('heroOverview').textContent=film.overview||'';$('selectedTitle').textContent=film.title;$('selectedYear').textContent=film.year||'';const bg=film.backdrop||film.poster||'';$('heroBackdrop').style.backgroundImage=bg?`url("${String(bg).replace(/"/g,'%22')}")`:'radial-gradient(circle at 65% 30%, rgba(36,183,255,.23), transparent 33%), linear-gradient(135deg,#071522,#02050a)';document.querySelectorAll('.category-card.active').forEach(el=>el.classList.remove('active'));document.querySelectorAll(`.category-card[data-film-id="${CSS.escape(film.id)}"]`).forEach(el=>el.classList.add('active'))}
function commitSelection(duration=240,withTick=true){if(!films.length)return;filmIndex=mod(virtualIndex,films.length);localStorage.setItem(STORAGE.selected,String(filmIndex));updateTrack(duration);updateFilmDetails();if(withTick)tick()}
function recenter(){if(!films.length||spinning)return;virtualIndex=MIDDLE_REPEAT*films.length+filmIndex;updateTrack(0)}
function move(delta){if(locked||spinning||!films.length)return;virtualIndex+=delta;commitSelection(220,true);setTimeout(recenter,240)}
function selectFilmById(id){const idx=films.findIndex(f=>f.id===id);if(idx<0)return;filmIndex=idx;virtualIndex=MIDDLE_REPEAT*films.length+filmIndex;localStorage.setItem(STORAGE.selected,String(filmIndex));updateTrack(250);updateFilmDetails();setTimeout(recenter,270);document.querySelector('.browse-area')?.scrollIntoView({behavior:'smooth',block:'start'})}
function randomTarget(){if(films.length<2)return filmIndex;let target=Math.floor(Math.random()*films.length);if(settings.avoidSame!==false)while(target===filmIndex)target=Math.floor(Math.random()*films.length);return target}
async function spin(){if(locked||spinning||films.length<2)return;spinning=true;$('spinBanner').hidden=false;virtualIndex=MIDDLE_REPEAT*films.length+filmIndex;updateTrack(0);const target=randomTarget(),cycles=3+Math.floor(Math.random()*3),deltaToTarget=mod(target-filmIndex,films.length)||films.length,totalSteps=cycles*films.length+deltaToTarget;for(let step=0;step<totalSteps;step++){const progress=step/Math.max(1,totalSteps-1),delay=30+Math.pow(progress,3.2)*270,transition=Math.max(22,Math.min(120,delay*.7));virtualIndex++;filmIndex=mod(virtualIndex,films.length);localStorage.setItem(STORAGE.selected,String(filmIndex));updateTrack(transition);updateFilmDetails();tick();await new Promise(r=>setTimeout(r,delay))}filmIndex=target;localStorage.setItem(STORAGE.selected,String(filmIndex));spinning=false;$('spinBanner').hidden=true;recenter()}
function tick(){if(!settings.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='square';osc.frequency.value=870+Math.random()*100;gain.gain.setValueAtTime(.045,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.028);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.032)}catch{}}
function toggleLock(){locked=!locked;$('lockBadge').hidden=!locked;$('lockButton').textContent=locked?'UNLOCK':'LOCK'}
function renderCategoryRows(){const order=['Comedy','Action & Adventure','Horror','Sci-Fi & Fantasy','Crime & Mystery','Thrillers','Family & Animation','Romance','Documentaries','Drama'];const groups=new Map();for(const cat of order){const list=films.filter(f=>(f.categories||[]).includes(cat));if(list.length)groups.set(cat,list)}const extras=[...new Set(films.flatMap(f=>f.categories||[]))].filter(c=>!groups.has(c));extras.forEach(cat=>groups.set(cat,films.filter(f=>(f.categories||[]).includes(cat))));categoryRows.innerHTML=[...groups.entries()].map(([cat,list])=>`<section class="category-row"><div class="row-heading"><h2>${escapeHtml(cat)}</h2><span>${list.length} title${list.length===1?'':'s'}</span></div><div class="category-strip">${list.map(f=>`<button class="category-card ${f.id===films[filmIndex]?.id?'active':''}" data-film-id="${escapeHtml(f.id)}" type="button" aria-label="Select ${escapeHtml(f.title)}">${f.poster?`<img src="${escapeHtml(f.poster)}" alt="${escapeHtml(f.title)} poster"/>`:`<div class="poster-placeholder">${escapeHtml(f.title)}</div>`}</button>`).join('')}</div></section>`).join('')}
let playActive=false,playTimeouts=[],adInterval=null,backFadeTimer=null,adSeconds=480,gamepadFrame=0,lastGamepadState='';
function clearPlayTimers(){playTimeouts.forEach(clearTimeout);playTimeouts=[];if(adInterval){clearInterval(adInterval);adInterval=null}clearTimeout(backFadeTimer);backFadeTimer=null}
function later(fn,ms){const id=setTimeout(fn,ms);playTimeouts.push(id);return id}
function updateAdCountdown(){const mins=Math.floor(adSeconds/60),secs=adSeconds%60;$('adCountdown').textContent=`${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`}
function playbackActivity(){if(!playActive)return;const back=$('playBackButton');back.classList.add('visible');clearTimeout(backFadeTimer);backFadeTimer=setTimeout(()=>back.classList.remove('visible'),3000)}
function startAdCountdown(){if(!playActive)return;adSeconds=480;updateAdCountdown();$('adLoading').hidden=false;$('playSequence').classList.add('ads-phase');playbackActivity();adInterval=setInterval(()=>{if(!playActive)return;adSeconds=Math.max(0,adSeconds-1);updateAdCountdown();if(adSeconds===0){clearInterval(adInterval);adInterval=null;reloadAdCycle()}},1000)}
function startLogoAdsCycle(){if(!playActive)return;const seq=$('playSequence');seq.classList.remove('ads-phase','reload-flicker');$('adLoading').hidden=true;seq.classList.remove('logo-phase');void seq.offsetWidth;seq.classList.add('logo-phase');later(()=>{if(!playActive)return;seq.classList.remove('logo-phase');startAdCountdown()},2200)}
function reloadAdCycle(){if(!playActive)return;const seq=$('playSequence');$('adLoading').hidden=true;seq.classList.remove('ads-phase');seq.classList.add('reload-flicker');later(()=>{if(!playActive)return;seq.classList.remove('reload-flicker');startLogoAdsCycle()},700)}
function playNow(){if(!films.length)return;closePlaySequence();const film=films[filmIndex],seq=$('playSequence'),art=$('playArtwork'),hero=document.querySelector('.hero'),r=hero.getBoundingClientRect();seq.style.setProperty('--hero-left',`${r.left}px`);seq.style.setProperty('--hero-top',`${r.top}px`);seq.style.setProperty('--hero-width',`${r.width}px`);seq.style.setProperty('--hero-height',`${r.height}px`);art.style.backgroundImage=(film.backdrop||film.poster)?`url("${String(film.backdrop||film.poster).replace(/"/g,'%22')}")`:'none';seq.hidden=false;seq.setAttribute('aria-hidden','false');seq.className='play-sequence';$('adLoading').hidden=true;playActive=true;void seq.offsetWidth;seq.classList.add('intro-phase');playbackActivity();later(()=>{if(!playActive)return;seq.classList.remove('intro-phase');seq.classList.add('black-phase');startLogoAdsCycle()},1650);pollGamepadActivity()}
function closePlaySequence(){playActive=false;clearPlayTimers();if(gamepadFrame)cancelAnimationFrame(gamepadFrame);gamepadFrame=0;lastGamepadState='';const seq=$('playSequence');seq.hidden=true;seq.className='play-sequence';seq.setAttribute('aria-hidden','true');$('adLoading').hidden=true;$('playBackButton').classList.remove('visible')}
function pollGamepadActivity(){if(!playActive)return;const pads=[...(navigator.getGamepads?.()||[])].filter(Boolean),state=pads.map(p=>`${p.buttons.map(b=>b.pressed?1:0).join('')}:${p.axes.map(a=>Math.abs(a)>.25?Math.sign(a):0).join(',')}`).join('|');if(state&&state!==lastGamepadState){if(lastGamepadState)playbackActivity();lastGamepadState=state}gamepadFrame=requestAnimationFrame(pollGamepadActivity)}
