const MAX=20*1024*1024;
export default{async fetch(req,env){const origin=req.headers.get('Origin')||'',cors=CORS(origin,env);if(req.method==='OPTIONS')return new Response(null,{status:cors.ok?204:403,headers:cors.h});if(!cors.ok)return J({error:'Origin not allowed.'},403,cors.h);const u=new URL(req.url);try{if(u.pathname==='/health'&&req.method==='GET')return J({ok:true},200,cors.h);if(u.pathname==='/state'&&req.method==='GET')return stateGet(env,cors.h);if(u.pathname==='/state'&&req.method==='PUT'){if(!await auth(req,env))return J({error:'Invalid edit PIN.'},401,cors.h);return statePut(req,env,cors.h)}if(u.pathname==='/asset'&&req.method==='POST'){if(!await auth(req,env))return J({error:'Invalid edit PIN.'},401,cors.h);return assetPost(req,env,cors.h)}if(u.pathname==='/asset'&&req.method==='GET')return assetGet(req,env,cors.h);return J({error:'Not found.'},404,cors.h)}catch(e){console.error(e);return J({error:e.message||'Server error.'},500,cors.h)}}};
function CORS(o,e){const a=String(e.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean),ok=!o||a.includes(o),h={'Vary':'Origin','Access-Control-Allow-Methods':'GET,PUT,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Edit-Pin,X-State-Sha,Range','Access-Control-Expose-Headers':'Content-Length,Content-Range,Accept-Ranges','Cache-Control':'no-store'};if(o&&ok)h['Access-Control-Allow-Origin']=o;return{ok,h}}
async function auth(r,e){const p=String(r.headers.get('X-Edit-Pin')||'').trim(),expected=String(e.EDIT_PIN||'').trim();if(!p||!expected)return false;return eq(await hash(p),await hash(expected))}async function hash(s){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}function eq(a,b){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
function GH(e,accept='application/vnd.github+json'){return{Accept:accept,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'Planuf-Checklist-Worker',Authorization:`Bearer ${e.GITHUB_TOKEN}`}}function base(e){return`https://api.github.com/repos/${encodeURIComponent(e.GITHUB_OWNER)}/${encodeURIComponent(e.GITHUB_REPO)}`}function ep(p){return String(p).split('/').map(encodeURIComponent).join('/')}function cu(e,p){return`${base(e)}/contents/${ep(p)}`}function sp(e){return e.STATE_PATH||'checklist/data/checklist.json'}function ap(e){return String(e.ASSET_PREFIX||'checklist/assets').replace(/^\/+|\/+$/g,'')}
function b64(s){const b=new TextEncoder().encode(s);return bb64(b)}function bb64(b){let x='';for(let i=0;i<b.length;i+=0x8000)x+=String.fromCharCode(...b.subarray(i,i+0x8000));return btoa(x)}function un64(s){const x=atob(String(s||'').replace(/\s/g,'')),b=new Uint8Array(x.length);for(let i=0;i<x.length;i++)b[i]=x.charCodeAt(i);return new TextDecoder().decode(b)}
async function meta(e,p,raw=false){const r=await fetch(`${cu(e,p)}?ref=${encodeURIComponent(e.GITHUB_BRANCH||'main')}`,{headers:GH(e,raw?'application/vnd.github.raw':'application/vnd.github+json')});if(r.status===404)return null;if(!r.ok)throw Error(`GitHub read failed (${r.status}).`);return raw?r:await r.json()}
async function readState(e){const m=await meta(e,sp(e));if(!m)return null;return{sha:m.sha||'',data:JSON.parse(un64(m.content))}}
async function stateGet(e,h){return J((await readState(e))||{sha:'',data:null},200,h)}
async function statePut(r,e,h){const body=await r.json(),data=body?.data;if(!data||!Array.isArray(data.shows))return J({error:'Invalid checklist data.'},400,h);const cur=await readState(e),cs=cur?.sha||'';if(cs&&String(body.baseSha||'')!==cs)return J({error:'Checklist changed on another device.'},409,h);const payload={message:'Save shared production checklist',content:b64(JSON.stringify(data,null,2)),branch:e.GITHUB_BRANCH||'main'};if(cs)payload.sha=cs;const wr=await fetch(cu(e,sp(e)),{method:'PUT',headers:{...GH(e),'Content-Type':'application/json'},body:JSON.stringify(payload)});if(wr.status===409)return J({error:'Checklist changed while saving.'},409,h);if(!wr.ok)throw Error(`GitHub write failed (${wr.status}).`);const out=await wr.json();return J({ok:true,sha:out.content?.sha||''},200,h)}
function seg(x){return String(x||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100)}function fn(x){return String(x||'asset').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').replace(/\s+/g,' ').trim().slice(0,150)||'asset'}
async function assetPost(r,e,h){const expected=r.headers.get('X-State-Sha')||'',cur=await readState(e),cs=cur?.sha||'';if(cs&&expected!==cs)return J({error:'Checklist changed on another device.'},409,h);const f=await r.formData(),file=f.get('file'),sid=seg(f.get('showId')),iid=seg(f.get('itemId'));if(!(file instanceof File)||!sid||!iid)return J({error:'Missing file information.'},400,h);const lim=Math.min(Number(e.MAX_ASSET_BYTES)||MAX,MAX);if(file.size>lim)return J({error:`File is larger than ${Math.floor(lim/1048576)} MB.`},413,h);const path=`${ap(e)}/${sid}/${iid}/${crypto.randomUUID()}-${fn(file.name)}`,bytes=new Uint8Array(await file.arrayBuffer()),payload={message:`Upload checklist asset: ${fn(file.name)}`,content:bb64(bytes),branch:e.GITHUB_BRANCH||'main'};const wr=await fetch(cu(e,path),{method:'PUT',headers:{...GH(e),'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!wr.ok)throw Error(`GitHub asset upload failed (${wr.status}).`);return J({ok:true,path},200,h)}
async function assetGet(r,e,h){const u=new URL(r.url),p=u.searchParams.get('path')||'';if(!p.startsWith(ap(e)+'/')||p.includes('..'))return J({error:'Invalid asset path.'},400,h);const headers=GH(e,'application/vnd.github.raw'),range=r.headers.get('Range');if(range)headers.Range=range;const gr=await fetch(`${cu(e,p)}?ref=${encodeURIComponent(e.GITHUB_BRANCH||'main')}`,{headers});if(gr.status===404)return J({error:'Asset not found.'},404,h);if(!gr.ok&&gr.status!==206)throw Error(`GitHub asset read failed (${gr.status}).`);const out={...h,'Content-Type':u.searchParams.get('type')||gr.headers.get('Content-Type')||'application/octet-stream','Cache-Control':'private,max-age=300'};for(const n of['Content-Length','Content-Range','Accept-Ranges']){const v=gr.headers.get(n);if(v)out[n]=v}return new Response(gr.body,{status:gr.status,headers:out})}
function J(d,s=200,h={}){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8',...h}})}